### ISSUE TITLE
Should plot use log="y" ?

### ISSUE THREAD

**Issue by eddelbuettel** [csgillespie/benchmarkme#5]
Those atom results pretty much destroy the useful information in the plot.

**Comment by csgillespie** [comment]
Good point. Will fix in the next version

**Comment by eddelbuettel** [comment]
:)

**Comment by eddelbuettel** [comment]
More methodological question:  score is sum of subtests?   Should we score [average] rankings?  

This is really useful by the way. Sitting at a new desktop that should be a screamer but isn't.

**Comment by csgillespie** [comment]
Yes, the y-axis (score) is just total time of all tests. This time is dominated by just four tests. My plan is as the sample size increases, the resolution of the reporting is more detailed. 

I like the idea of scoring the ranks (will investigate).

Since I have your attention two quick questions:
- Do you know if  `R CMD config BLAS_LIBS` works under Windows/Mac?
- So far very few (if any) users set `R_COMPILE_PKGS=3` in the Renviron or byte compile. Is there a downside to byte compiling I don't know about.

**Comment by eddelbuettel** [comment]
Don't know about either of those two bullet points, sorry.  I guess I could try Windows in the VM at work tomorrow.

**Comment by csgillespie** [comment]
Fixed by 570157be72ec367551abfad26efefd47e46687cd
